### ISSUE TITLE
String literals will be replaced by SourceCode::replace_args 

### ISSUE THREAD

**Issue by spierceVR** [MinecraftU/2022-computer-adventures-pringlelang#37]
In functions, argument names surrounded by spaces inside strings will be replaced by their values. We need to update the SourceCode::replace_args function to fix this.

_Originally posted by @jamespeilunli in https://github.com/MinecraftU/2022-computer-adventures-pringlelang/issues/32#issuecomment-1206769408_

**Comment by jamespeilunli** [comment]
@spierceVR what do you think about putting arguments (arg name to arg value) into the `variables` map (treating arguments as variables, creating a special function "scope" for the arguments) at the start of a function call, and then erasing them once the function is called (instead of having a `replace_args` function)? I believe this would be faster and more readable. Plus, we probably won't encounter this type of bug again.

**Comment by spierceVR** [comment]
> @spierceVR what do you think about putting arguments (arg name to arg value) into the `variables` map (treating arguments as variables, creating a special function "scope" for the arguments) at the start of a function call, and then erasing them once the function is called (instead of having a `replace_args` function)? I believe this would be faster and more readable. Plus, we probably won't encounter this type of bug again.

Yeah that sounds like a good way of doing it. Then we can also get rid of the copy of the source code that we're making whenever we parse a function definition. Instead of copying the body of the function and storing it in a SourceCode object we can just store the location of the beginning of the function within the program's SourceCode string
